# Using FBApro

FBApro projects a matrix with shape `samples x reactions` of reaction fluxes onto the steady-state space $\ker(S)$ of a metabolic model, returning for each sample the closest steady-state flux vectors, optionally holding some reactions fixed and ignoring others.

All variants are implemented by the single `FBApro` class, initialized with a stoichiometric matrix, and the lists "measured_indices" and "unknown_indices" defining which reactions must be fixed as the input and which are ignored in minimizing distances. Passing empty lists or None corresponds to simpler variants of FBApro:

| `measured_indices` | `unknown_indices` | `.name` | behaviour |
|--------------------|-------------------| --- | --- |
| Empty              | Empty             | `FBAproBasic` | closest steady-state flux to the input |
| Empty              | Given             | `FBAproPartial` | closest steady-state flux, ignoring the unknown reactions when measuring distance |
| Given              | Empty             | `FBAproFixed` | closest steady-state flux that keeps the measured reactions at their input values |
| Given              | Given             | `FBAproFull` | keeps the measured reactions fixed *and* ignores the unknown ones in the distance |

`measured_indices` and `unknown_indices` must be disjoint.

In [1]:
import os
import sys
import warnings

# projection_methods is in the repository root, one level above this notebook
repository_root = os.path.abspath("..")
if repository_root not in sys.path:
    sys.path.insert(0, repository_root)

import cobra
import numpy as np
np.object = object
import torch
from projection_methods import FBApro
warnings.filterwarnings("ignore", message="To copy construct from a tensor")

cpu = torch.device("cpu")
torch.set_printoptions(precision=4, sci_mode=False)

# FBApro's internal matrices and linear algebra method calls are conditioned with an absolute threshold acond, and a relative threshold rcond: entries smaller than acond are zeroed, and similarly matrix singular values with relative weight of rcond compared to the maximal singular value. The default is acond=0, rcond=1e-3, appropriate values may need to be empirically determined for different models and data sets, typically a small nonzero acond (significantly smaller than all stoichiometric coefficients) is useful for measured_indices leaving zero degrees of freedom, and a small nonzero rcond for big models and numerically unstable stoichiometric matrices.
ACOND = 1e-5

C:\Users\Ariel\PycharmProjects\FBApro\venv\lib\site-packages\cobamp\wrappers\external_wrappers.py:9: UserWarning: 
The wrappers.external_wrappers module will be deprecated in a future release in favour of the wrappers module. 
    Available ModelObjectReader classes can still be loaded using cobamp.wrappers.<class>. An appropriate model 
    reader can also be created using the get_model_reader function on cobamp.wrappers
  warnings.warn(


# A single linear pathway
<table><tr><td>
<img src="models/single_pathway.png">
</td><td>
        $$
        S=\begin{array}{cc}
        & \begin{array}{ccc} r1 & r2 & r3 \end{array} \\
        \begin{array}{c} \text{A} \\ \text{B} \end{array} &
        \left(
            \begin{array}{ccc}
            1 & -1 & 0 \\
            0 & 1 & -1 \\
            \end{array}
        \right)
        \end{array}
        $$
</td></tr></table>

Every steady-state flux of this model has the form $(x, x, x)$.

In [2]:
model = cobra.io.read_sbml_model("models/single_pathway.xml")
S = cobra.util.create_stoichiometric_matrix(model)
print([r.id for r in model.reactions])
print(S)

Set parameter Username
Set parameter LicenseID to value 2789968
Academic license - for non-commercial use only - expires 2027-03-10


No objective coefficients in model. Unclear what should be optimized


['import_A', 'A_to_B', 'export_B']
[[ 1. -1.  0.]
 [ 0.  1. -1.]]


## Denoising a given flux vector

With neither index list given, `FBApro` is a plain projection onto the steady-state space.

In [3]:
fbapro = FBApro(stoichiometric_matrix=S, device=cpu, acond=ACOND)
print(fbapro.name)

# input is expected as a samples x reactions matrix
noisy_input = torch.tensor([[1.0, 1.0, 1.0],
                            [1.9, 2.0, 2.1],
                            [1.0, 2.0, 0.0],
                            [1.0, 0.0, 1.0]], device=cpu, dtype=torch.float64)
fbapro(noisy_input)

FBAproBasic


tensor([[1.0000, 1.0000, 1.0000],
        [2.0000, 2.0000, 2.0000],
        [1.0000, 1.0000, 1.0000],
        [0.6667, 0.6667, 0.6667]], dtype=torch.float64)

## FBAproPartial: reactions with no data

Distance minimization is solved only over reactions not in `unknown_indices`, subject to the result across all reactions being in steady-state.

Recall that
</td><td>
        $$
        \text{noisy\_input}=\begin{array}{cc}
        \left(
            \begin{array}{ccc}
            1 & 1 & 1 \\
            1.9 & 2 & 2.1 \\
            1 & 2 & 0 \\
            1 & 0 & 1 \\
            \end{array}
        \right)
        \end{array}
        $$
</td></tr></table>

In [4]:
unknown_indices = [1]  # zero based indexing: the A --> B reaction
fbapro_partial = FBApro(stoichiometric_matrix=S, unknown_indices=unknown_indices, device=cpu, acond=ACOND)
print(fbapro_partial.name)
fbapro_partial(noisy_input)

FBAproPartial


tensor([[1.0000, 1.0000, 1.0000],
        [2.0000, 2.0000, 2.0000],
        [0.5000, 0.5000, 0.5000],
        [1.0000, 1.0000, 1.0000]], dtype=torch.float64)

## FBAproFixed: reactions with high confidence

Steady-state outputs respect, if possible, equality constraints on the fixed values in `measured_indices`. In this linear pathway, fixing any
single reaction fully determines the corresponding steady-state flux.

Recall that
</td><td>
        $$
        \text{noisy\_input}=\begin{array}{cc}
        \left(
            \begin{array}{ccc}
            1 & 1 & 1 \\
            1.9 & 2 & 2.1 \\
            1 & 2 & 0 \\
            1 & 0 & 1 \\
            \end{array}
        \right)
        \end{array}
        $$
</td></tr></table>

In [5]:
measured_indices = [2]  # the export_B reaction
fbapro_fixed = FBApro(stoichiometric_matrix=S, measured_indices=measured_indices, device=cpu, acond=ACOND)
print(fbapro_fixed.name)
fbapro_fixed(noisy_input)

FBAproFixed


tensor([[     1.0000,      1.0000,      1.0000],
        [     2.1000,      2.1000,      2.1000],
        [    -0.0000,     -0.0000,     -0.0000],
        [     1.0000,      1.0000,      1.0000]], dtype=torch.float64)

</td><td>
        $$
        \text{noisy\_input}=\begin{array}{cc}
        \left(
            \begin{array}{ccc}
            1 & 1 & 1 \\
            1.9 & 2 & 2.1 \\
            1 & 2 & 0 \\
            1 & 0 & 1 \\
            \end{array}
        \right)
        \end{array}
        $$
</td></tr></table>

### Fully specified confitions

Note that the computation on a fully determined system is numerically unstable, especially with acond=0. FBApro prints a warning when output significantly varies from steady-state:

In [6]:
fbapro_fixed = FBApro(stoichiometric_matrix=S, measured_indices=[2], device=cpu, acond=0)
fbapro_fixed(noisy_input)

Input - abs min: 0.00e+00, abs max: 2.10e+00, abs mean: 1.17e+00
output - abs min: 7.89e-02, abs max: 2.05e+00, abs mean: 1.17e+00
S * output - abs min: 0.00e+00, abs max: 1.97e+00, abs mean: 6.21e-01
Suppressing further warnings.


tensor([[1.0000, 1.0000, 1.0000],
        [2.0053, 1.9579, 2.0368],
        [0.8684, 2.0526, 0.0789],
        [0.7368, 0.1053, 1.1579]], dtype=torch.float64)

### Inconsistent measurements

The input fixed values may be inconsistent with the steady-state space. Behavior is undefined on these inputs, but typically FBApro will return a steady-state flux minimizing flux distance to the fixed values.

Recall that
</td><td>
        $$
        \text{noisy\_input}=\begin{array}{cc}
        \left(
            \begin{array}{ccc}
            1 & 1 & 1 \\
            1.9 & 2 & 2.1 \\
            1 & 2 & 0 \\
            1 & 0 & 1 \\
            \end{array}
        \right)
        \end{array}
        $$
</td></tr></table>

In [7]:
fbapro_inconsistent = FBApro(stoichiometric_matrix=S, measured_indices=[0, 2], device=cpu, acond=ACOND)
fbapro_inconsistent(noisy_input)

tensor([[1.0000, 1.0000, 1.0000],
        [2.0000, 2.0000, 2.0000],
        [0.5000, 0.5000, 0.5000],
        [1.0000, 1.0000, 1.0000]], dtype=torch.float64)

# A branching pathway
<table><tr><td>
<img src="models/branching_pathway.png">
</td><td>
        $$
        S=\begin{array}{cc}
        & \begin{array}{ccc} r1 & r2 & r3 & r4 & r5 \end{array} \\
        \begin{array}{c} \text{A} \\\text{Right} \\ \text{Left} \end{array} &
        \left(
            \begin{array}{ccc}
            1 & -1 & 0 & -1 & 0 \\
            0 & 1 & -1 & 0 & 0\\
            0 & 0 & 0 & 1 & -1\\
            \end{array}
        \right)
        \end{array}
        $$
</td></tr></table>

There are two degrees of freedom here: steady-state fluxes are of the form
$(a+b,\ a,\ a,\ b,\ b)$. Any three reactions, and any two reactions not in the same branch, determine
the corresponding steady-state fluxes.

In [8]:
model = cobra.io.read_sbml_model("models/branching_pathway.xml")
S = cobra.util.create_stoichiometric_matrix(model)
print([r.id for r in model.reactions])
print(S)

noisy_input = torch.tensor([[5.0, 2.0, 2.0, 3.0, 3.0],
                            [5.0, 2.0, 2.5, 3.0, 2.5],
                            [10.0, 2.0, 2.5, 3.0, 2.5],
                            [5.0, 0.0, 0.0, 3.0, 3.0],
                            [5.0, 0.0, 0.0, 5.0, 5.0]], device=cpu, dtype=torch.float64)

fbapro = FBApro(stoichiometric_matrix=S, device=cpu, acond=ACOND)
print(fbapro.name)
fbapro(noisy_input)

No objective coefficients in model. Unclear what should be optimized


['import_A', 'A_to_Right', 'export_Right', 'A_to_Left', 'export_Left']
[[ 1. -1.  0. -1.  0.]
 [ 0.  1. -1.  0.  0.]
 [ 0.  0.  0.  1. -1.]]
FBAproBasic


tensor([[     5.0000,      2.0000,      2.0000,      3.0000,      3.0000],
        [     5.0000,      2.2500,      2.2500,      2.7500,      2.7500],
        [     7.5000,      3.5000,      3.5000,      4.0000,      4.0000],
        [     4.0000,      0.5000,      0.5000,      3.5000,      3.5000],
        [     5.0000,     -0.0000,      0.0000,      5.0000,      5.0000]],
       dtype=torch.float64)

</td><td>
        $$
        \text{noisy\_input}=\begin{array}{cc}
        \left(
            \begin{array}{ccccc}
            5 & 2 & 2 & 3 & 3 \\
            5 & 2 & 2.5 & 3 & 2.5 \\
            10 & 2 & 2.5 & 3 & 2.5 \\
            5 & 0 & 0 & 3 & 3 \\
            5 & 0 & 0 & 5 & 5 \\
            \end{array}
        \right)
        \end{array}
        $$
</td></tr></table>

## Ignoring a branch with no data

Treating the right branch (`A_to_Right`, `export_Right`) as unknown lets the left branch and the
import determine it, with distance minimization where the input fluxes are inconsistent.

In [9]:
fbapro_partial = FBApro(stoichiometric_matrix=S, unknown_indices=[1, 2], device=cpu, acond=ACOND)
print(fbapro_partial.name)
partial_output = fbapro_partial(noisy_input)
partial_output

FBAproPartial


tensor([[     5.0000,      2.0000,      2.0000,      3.0000,      3.0000],
        [     5.0000,      2.2500,      2.2500,      2.7500,      2.7500],
        [    10.0000,      7.2500,      7.2500,      2.7500,      2.7500],
        [     5.0000,      2.0000,      2.0000,      3.0000,      3.0000],
        [     5.0000,     -0.0000,      0.0000,      5.0000,      5.0000]],
       dtype=torch.float64)

Fixing the import and left branch determines a single
steady-state flux, so `FBAproFixed` with these as fixed reproduces the same outputs (up to numerical noise).

In [10]:
fbapro_fixed = FBApro(stoichiometric_matrix=S, measured_indices=[0, 3, 4], device=cpu, acond=ACOND)
print(fbapro_fixed.name)
fixed_output = fbapro_fixed(noisy_input)
print(fixed_output)
print(np.isclose(fixed_output.numpy(), partial_output.numpy(), atol=1e-5))

FBAproFixed
tensor([[    5.0000,     2.0000,     2.0000,     3.0000,     3.0000],
        [    5.0000,     2.2500,     2.2500,     2.7500,     2.7500],
        [   10.0000,     7.2500,     7.2500,     2.7500,     2.7500],
        [    5.0000,     2.0000,     2.0000,     3.0000,     3.0000],
        [    5.0000,     0.0000,     0.0000,     5.0000,     5.0000]],
       dtype=torch.float64)
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


Fixing only the import leaves one degree of freedom, so the total flux is fixed with the branch split minimizing distance from input.

Recall that

</td><td>
        $$
        \text{noisy\_input}=\begin{array}{cc}
        \left(
            \begin{array}{ccccc}
            5 & 2 & 2 & 3 & 3 \\
            5 & 2 & 2.5 & 3 & 2.5 \\
            10 & 2 & 2.5 & 3 & 2.5 \\
            5 & 0 & 0 & 3 & 3 \\
            5 & 0 & 0 & 5 & 5 \\
            \end{array}
        \right)
        \end{array}
        $$
</td></tr></table>

In [11]:
fbapro_fixed_import = FBApro(stoichiometric_matrix=S, measured_indices=[0], device=cpu, acond=ACOND)
fbapro_fixed_import(noisy_input)

tensor([[     5.0000,      2.0000,      2.0000,      3.0000,      3.0000],
        [     5.0000,      2.2500,      2.2500,      2.7500,      2.7500],
        [    10.0000,      4.7500,      4.7500,      5.2500,      5.2500],
        [     5.0000,      1.0000,      1.0000,      4.0000,      4.0000],
        [     5.0000,     -0.0000,      0.0000,      5.0000,      5.0000]],
       dtype=torch.float64)

## FBAproFull: measured and unknown reactions together

With the import fixed and the left branch ignored, FBAproFull returns the single steady-state flux vector agreeing with the import and the right branch, as FBAproFixed would with the import and right branch fixed.

Recall that

</td><td>
        $$
        \text{noisy\_input}=\begin{array}{cc}
        \left(
            \begin{array}{ccccc}
            5 & 2 & 2 & 3 & 3 \\
            5 & 2 & 2.5 & 3 & 2.5 \\
            10 & 2 & 2.5 & 3 & 2.5 \\
            5 & 0 & 0 & 3 & 3 \\
            5 & 0 & 0 & 5 & 5 \\
            \end{array}
        \right)
        \end{array}
        $$
</td></tr></table>

In [12]:
fbapro_full = FBApro(stoichiometric_matrix=S, measured_indices=[0], unknown_indices=[3, 4],
                     device=cpu, acond=ACOND)
print(fbapro_full.name)
full_output = fbapro_full(noisy_input)
print(full_output)

FBAproFull
tensor([[     5.0000,      2.0000,      2.0000,      3.0000,      3.0000],
        [     5.0000,      2.2500,      2.2500,      2.7500,      2.7500],
        [    10.0000,      2.2500,      2.2500,      7.7500,      7.7500],
        [     5.0000,      0.0000,      0.0000,      5.0000,      5.0000],
        [     5.0000,     -0.0000,      0.0000,      5.0000,      5.0000]],
       dtype=torch.float64)


With the import fixed and exports ignored, FBAproFull returns the steady-state with the given import closest to the A --> B and B --> C split in the input.

Recall that

</td><td>
        $$
        \text{noisy\_input}=\begin{array}{cc}
        \left(
            \begin{array}{ccccc}
            5 & 2 & 2 & 3 & 3 \\
            5 & 2 & 2.5 & 3 & 2.5 \\
            10 & 2 & 2.5 & 3 & 2.5 \\
            5 & 0 & 0 & 3 & 3 \\
            5 & 0 & 0 & 5 & 5 \\
            \end{array}
        \right)
        \end{array}
        $$
</td></tr></table>

In [13]:
fbapro_full = FBApro(stoichiometric_matrix=S, measured_indices=[0], unknown_indices=[2, 4],
                     device=cpu, acond=ACOND)
print(fbapro_full.name)
full_output = fbapro_full(noisy_input)
print(full_output)

FBAproFull
tensor([[    5.0000,     2.0000,     2.0000,     3.0000,     3.0000],
        [    5.0000,     2.0000,     2.0000,     3.0000,     3.0000],
        [   10.0000,     4.5000,     4.5000,     5.5000,     5.5000],
        [    5.0000,     1.0000,     1.0000,     4.0000,     4.0000],
        [    5.0000,     0.0000,     0.0000,     5.0000,     5.0000]],
       dtype=torch.float64)


With the import fixed and only the left branch export ignored, FBAproFull gives the right branch more weight in the minimization, so the output is closer to the inputs on the right branch than the left.

Recall that

</td><td>
        $$
        \text{noisy\_input}=\begin{array}{cc}
        \left(
            \begin{array}{ccccc}
            5 & 2 & 2 & 3 & 3 \\
            5 & 2 & 2.5 & 3 & 2.5 \\
            10 & 2 & 2.5 & 3 & 2.5 \\
            5 & 0 & 0 & 3 & 3 \\
            5 & 0 & 0 & 5 & 5 \\
            \end{array}
        \right)
        \end{array}
        $$
</td></tr></table>

In [14]:
fbapro_full = FBApro(stoichiometric_matrix=S, measured_indices=[0], unknown_indices=[4],
                     device=cpu, acond=ACOND)
print(fbapro_full.name)
full_output = fbapro_full(noisy_input)
print(full_output)

FBAproFull
tensor([[     5.0000,      2.0000,      2.0000,      3.0000,      3.0000],
        [     5.0000,      2.1667,      2.1667,      2.8333,      2.8333],
        [    10.0000,      3.8333,      3.8333,      6.1667,      6.1667],
        [     5.0000,      0.6667,      0.6667,      4.3333,      4.3333],
        [     5.0000,     -0.0000,      0.0000,      5.0000,      5.0000]],
       dtype=torch.float64)


# A roundabout, or cycle of reactions
<table><tr><td>
<img src="models/roundabout.png">
</td><td>
        $$
        S=\begin{array}{cc}
        & \begin{array}{cccccc} r1 & r2 & r3 & r4 & r5 & r6\end{array} \\
        \begin{array}{c} \text{A} \\ \text{B} \\ \text{C}\end{array} &
        \left(
            \begin{array}{cccccc}
            1 & 0 & 0 & -1 & 0 & 1\\
            0 & 1 & 0 & 1 & -1 & 0\\
            0 & 0 & 1 & 0 & 1 & -1\\
            \end{array}
        \right)
        \end{array}
        $$
</td></tr></table>

This model has three metabolites, three
import/exports and a cycle $A \to B \to C \to A$.

In [15]:
model = cobra.io.read_sbml_model("models/roundabout.xml")
S = cobra.util.create_stoichiometric_matrix(model)
print([r.id for r in model.reactions])
print(S)
print("reaction bounds:", [r.bounds for r in model.reactions])

No objective coefficients in model. Unclear what should be optimized


['import_A', 'import_B', 'import_C', 'A_to_B', 'B_to_C', 'C_to_A']
[[ 1.  0.  0. -1.  0.  1.]
 [ 0.  1.  0.  1. -1.  0.]
 [ 0.  0.  1.  0.  1. -1.]]
reaction bounds: [(0.0, 1000.0), (0.0, 1000.0), (0.0, 1000.0), (0.0, 1000.0), (0.0, 1000.0), (0.0, 1000.0)]


In [16]:
noisy_input = torch.tensor([[0.0, 0.0, 0.0, 1.0, 1.0, 1.0],    # pure cycle flux: already a steady state
                            [1.0, 0.0, 0.0, 1.0, 1.0, 1.0],    # one import carries flux
                            [1.0, 1.0, -2.0, 3.0, 4.0, 2.0],   # steady, but import_C is negative
                            [0.0, 0.0, 0.0, 5.0, 0.0, 0.0]],   # only one cycle step carries flux
                           device=cpu, dtype=torch.float64)

</td><td>
        $$
        \text{noisy\_input}=\begin{array}{ccl}
        \left(
            \begin{array}{cccccc}
            0 & 0 & 0 & 1 & 1 & 1 \\
            1 & 0 & 0 & 1 & 1 & 1 \\
            1 & 1 & -2 & 3 & 4 & 2 \\
            0 & 0 & 0 & 5 & 0 & 0 \\
            \end{array}
        \right) &
        \begin{array}{l}
        \text{flux only throuhg the cycle} \\
        \text{cycle flux and one extra import, non-steady} \\
        \text{steady flux using both the cycle and import-exports} \\
        \text{flux throuhg a single cycle reaction}
        \end{array}
        \end{array}
        $$
</td></tr></table>

In [17]:
fbapro = FBApro(stoichiometric_matrix=S, device=cpu, acond=ACOND)
print(fbapro.name)

output = fbapro(noisy_input)
print(output)

FBAproBasic
tensor([[    -0.0000,      0.0000,      0.0000,      1.0000,      1.0000,
              1.0000],
        [     0.5000,     -0.2500,     -0.2500,      1.2500,      1.0000,
              0.7500],
        [     1.0000,      1.0000,     -2.0000,      3.0000,      4.0000,
              2.0000],
        [     1.2500,     -1.2500,      0.0000,      2.5000,      1.2500,
              1.2500]], dtype=torch.float64)


Note that FBApro treats all reactions as reversible, and that by default favors matching input fluxes on futile cycles as much as on import-export pathways. Fixing the imports and exports and/or ignoring the cycle fluxes sets them as higher priority (with inconsistencies resulting in distance minimization).

Recall that
</td><td>
        $$
        \text{noisy\_input}=\begin{array}{ccl}
        \left(
            \begin{array}{cccccc}
            0 & 0 & 0 & 1 & 1 & 1 \\
            1 & 0 & 0 & 1 & 1 & 1 \\
            1 & 1 & -2 & 3 & 4 & 2 \\
            0 & 0 & 0 & 5 & 0 & 0 \\
            \end{array}
        \right) &
        \begin{array}{l}
        \text{flux only throuhg the cycle} \\
        \text{cycle flux and one extra import, non-steady} \\
        \text{steady flux using both the cycle and import-exports} \\
        \text{flux throuhg a single cycle reaction}
        \end{array}
        \end{array}
        $$
</td></tr></table>

In [18]:
fbapro_fixed = FBApro(stoichiometric_matrix=S, measured_indices=[0, 1, 2], device=cpu, acond=ACOND)
print(fbapro_fixed.name)
fbapro_fixed(noisy_input)

FBAproFixed


tensor([[     0.0000,      0.0000,     -0.0000,      1.0000,      1.0000,
              1.0000],
        [     0.6667,     -0.3333,     -0.3333,      1.3333,      1.0000,
              0.6667],
        [     1.0000,      1.0000,     -2.0000,      3.0000,      4.0000,
              2.0000],
        [    -0.0000,      0.0000,     -0.0000,      1.6667,      1.6667,
              1.6667]], dtype=torch.float64)

In [19]:
fbapro_fixed = FBApro(stoichiometric_matrix=S, unknown_indices=[3, 4, 5], device=cpu, acond=ACOND)
print(fbapro_fixed.name)
fbapro_fixed(noisy_input)

FBAproPartial


tensor([[     0.0000,      0.0000,      0.0000,      0.0000,      0.0000,
              0.0000],
        [     0.6667,     -0.3333,     -0.3333,      0.3333,     -0.0000,
             -0.3333],
        [     1.0000,      1.0000,     -2.0000,     -0.0000,      1.0000,
             -1.0000],
        [     0.0000,      0.0000,      0.0000,      0.0000,      0.0000,
              0.0000]], dtype=torch.float64)